---
- name: Install NginX
  dnf:
    state: present
    name:
      - nginx

- name: Set httpd_can_network_connect flag in SELINUX
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: Customize nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '0644'
  notify: "restart nginx"
