---
galaxy_info:
  role_name: auth_centos8
  author: Sido Haakma
  description: Armadillo authentication implementation used allow people to use the Armadillo suite
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
   - name: CentOS
     versions:
     - 8
     - 7
   - name: RHEL
     versions:
     - 8
     - 7

  galaxy_tags: [federation]

allow_duplicates: true

dependencies:
  - { role: podman_centos8 }
