---
galaxy_info:
  role_name: rserver_debian10
  author: Sido Haakma
  description: RServer implementation used to perform local analysis and send aggregated results to the Aramdillo
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
   - name: Debian
     versions:
     - 10.4

  galaxy_tags: [federation]

allow_duplicates: true

dependencies:
  - { role: docker_debian10 }
    
