---
- name: disable password login | Configuration
  lineinfile:
    path: '/etc/ssh/sshd_config'
    regexp: '^(.*)PasswordAuthentication(.*)$'
    line: 'PasswordAuthentication no'
  notify: 'restart sshd service'
  when: enabled

- name: configure firewall



