---

- name: remove old versions of docker
  apt:
    state: absent
    name:
      - docker 
      - docker-engine 
      - docker.io 
      - containerd 
      - runc

- name: install docker prerequisites
  apt:
    state: present
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: add keyring
  ansible.builtin.apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add docker repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
    state: present
  
- name: install docker
  apt:
    update_cache: yes
    state: present
    name:
      - docker-ce 
      - docker-ce-cli 
      - containerd.io