---
- name: determine docker service based upon OS
  set_fact:
    docker_service: "{% if ansible_os_family == 'Debian'%}docker{% endif %}{% if ansible_os_family == 'RedHat'%}podman{% endif %}"

- name: create folder for RServer logs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0644'
  with_items:
    - /var/log/rserver
    - /etc/rserver

- name: generate systemd file for RServer
  template:
    src: rserver.j2
    dest: /etc/systemd/system/rserver.service
    mode: '0644'
  notify: "restart Rserver service"

- name: generate env.list for RServer
  template:
    src: env.j2
    dest: /etc/rserver/env.list
    mode: '0644'
  notify: "restart Rserver service"

- name: log into DockerHub
  docker_login:
    username: "{{ dockerhub.username }}"
    password: "{{ dockerhub.password }}"
  when: dockerhub.enabled and ansible_os_family == 'Debian'

- name: pull RServer image
  docker_image:
    name: "{{ image.repo }}/{{ image.name }}"
    tag: "{{ image.version }}"
    state: present 
    source: pull
  when: ansible_os_family == 'Debian'

- name: enable RServer service
  systemd:
    name: rserver
    enabled: yes
    masked: no
