---
- name: determine docker service based upon OS
  set_fact:
    docker.service: "{% if ansible_os_family == 'Ubuntu' or ansible_os_family == 'Debian'%}docker{% endif %}{% if ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'%}podman{% endif %}"

- name: create folder for RServer logs
  file:
    path: "{{ item }}"
    state: directory
    mode: '0644'
  with_items:
    - /var/log/rserver
    - /etc/rserver

- name: generate systemd file
  template:
    src: rserver.j2
    dest: /etc/systemd/system/rserver.service
    mode: '0644'
  notify: "restart Rserver service"

- name: generate env.list for rserver
  template:
    src: env.j2
    dest: /etc/rserver/env.list
    mode: '0644'
  notify: "restart Rserver service"

- name: enable rserver service
  systemd:
    name: rserver
    enabled: yes
    masked: no
