---
galaxy_info:
  role_name: docker_ubuntu20
  author: Sido Haakma
  description: Docker used to run containers on the OS
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
   - name: Ubuntu
     versions:
     - 20.04

  galaxy_tags: [federation]

dependencies: []
