---
galaxy_info:
  role_name: podman
  author: Sido Haakma
  description: Podman used to run docker images on a Redhat/CentOS system
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
   - name: CentOS
     versions:
     - 8
   - name: RHEL
     versions:
     - 8

  galaxy_tags: [federation]

dependencies: []
