---
galaxy_info:
  role_name: docker_debian10
  author: Sido Haakma
  description: Docker used to run containers on the OS
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
   - name: Debian
     versions:
     - 10.4

  galaxy_tags: [federation]

dependencies: []
