---
- name: Deployment for MOLGENIS - operational development
  hosts: "{{ host_group }}"
  gather_facts: true
  become: true
  vars:
    host_group: "all"
    experimental: false
    ci: false
    molgenis:
      setup: true
      version: 5.23.1
      ssh: true
      
  roles:
    # system configuration
    - role: molgenis.molgenis8.swap_centos8
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'
    - role: molgenis.molgenis8.preinstall_centos8
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'
    # application configuration
    - role: molgenis.molgenis8.java_centos8
      vars:
        version: 13
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'
    - role: postgres_13_centos8
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'
    - role: emx2_centos8
      when: ansible_distribution == "CentOS" and ansible_distribution_major_version == '8'

    - role: postinstall
