# required
namespace: molgenis

name: armadillo

version: 2.0.8

readme: README.md

authors:
- Christian Hilbrands
- Dick Postma
- Sido Haakma

# optional
description: Armadillo is a service which can be used to perform federated analysis

license:
- LGPL-2.0-or-later

tags: [federation]

repository: https://github.com/molgenis/molgenis-ops-galaxy/tree/main/armadillo1

documentation: https://github.com/molgenis/molgenis-service-armadillo

homepage: https://data-catalogue.molgeniscloud.org/apps/docs/#/armadillo/

issues: https://github.com/molgenis/molgenis-service-armadillo/issues
