---
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  vars:
    ci: false
    minio:
      access_key: molgenis
      secret_key: molgenis
      port: 9000
      host: http://localhost
    oauth:
      issuer_uri: https://auth.molgenis.org
      discovery_path: /.well-known/openid-configuration
      client_id: b396233b-cdb2-449e-ac5c-a0d28b38f791

  roles:
    - role: molgenis.molgenis8.preinstall_centos8
    - role: molgenis.molgenis8.java_centos8
    - role: molgenis.molgenis8.minio_centos8
      vars:
        access_key: "{{ minio.access_key }}"
        secret_key: "{{ minio.secret_key }}"
    - role: podman_centos8
    - role: nginx_centos8
      vars:
        host: armadillo.local
        ports:
          armadillo: 8080
          storage: "{{ minio.port }}"
          auth: 4000
    - role: rserver_centos8
      vars:
        debug: true
    - role: armadillo_centos8
      vars:
        version: 0.0.15
        storage:
          access_key: "{{ minio.access_key }}"
          secret_key: "{{ minio.secret_key }}"
          host: "{{ minio.host }}"
          port: "{{ minio.port }}"
    - role: auth_centos8
      vars:
        image: 
          version: 0.2.0
        oauth:
          issuer_uri: "{{ oauth.issuer_uri }}"
          client_id: "{{ oauth.client_id }}"
          client_secret: xxxxx-xxxxx-xxxxx
          api_token: xxxx-xxxxx-xxxxx
