---
- hosts: all # needs to be: 'localhost' if local connection is set
  become: true
  # connection: local 
  become_user: root
  gather_facts: true

  roles:
    - role: tools_cleanup
      vars:
        packages:
          - armadillo
          - armadillo-auth
          - minio
          - rserver
        dependencies:
          java:
            version: 11
