---
- hosts: all
  become: true
  # connection: local
  become_user: root
  gather_facts: true
  vars:
    ci: false
    minio:
      root_user: xxxxxxxx
      root_password: xxxxxxxx
      port: 9000
      domain: armadillo-storage.local
      host: http://minio
      console:
        enabled: true
        port: 9090
        domain: armadillo-storage-console.local
    oauth:
      issuer_uri: https://auth.molgenis.org
      discovery_path: .well-known/openid-configuration
      client_id: xxxxxxxxx-xxxxxx-xxxxxxxxx-xxxxxxx
      client_secret: xxxxxxxxx-xxxxxx-xxxxxxxxx-xxxxxxx
    rserve:
      environments:
        - name: default
          enabled: true
          debug: false
          image:
            version: latest
            repo: datashield
            name: armadillo-rserver
          exposed_port: 6311
        - name: mediation
          enabled: true
          debug: false
          image:
            version: latest
            repo: datashield
            name: armadillo-rserver-mediation
          exposed_port: 6311

  roles:
    - role: deps_podman
      vars:
        redhat:
          subscription:
            enabled: false
            username: xxxxxxxx
            password: xxxxxxxx
      when: ansible_distribution == "RedHat" or ansible_distribution == "Rocky"
    - role: deps_docker
      when: ansible_os_family == "Debian" or ansible_distribution == "CentOS"
    - role: deps_compose
    - role: service_armadillo
      vars:
        version: 2.2.2
        storage:
          root_user: "{{ minio.root_user }}"
          root_password: "{{ minio.root_password }}"
          host: "{{ minio.host }}"
          port: "{{ minio.port }}"
        memory:
          xmx: 1024m
          xms: 512m
        username: xxxxxx
        password: xxxxxx
        datashield:
          profiles:
            - name: "{{ rserve.environments[0].name }}"
              enabled: "{{ rserve.environments[0].enabled }}"
              environment: "{{ rserve.environments[0].name }}"
              whitelist:
                - dsBase
              # options:
                # datashield:
                  # a: b
                  # override default DataSHIELD thresholds
            - name: "{{ rserve.environments[1].name }}"
              enabled: "{{ rserve.environments[1].enabled }}"
              environment: "{{ rserve.environments[1].name }}"
              whitelist:
                - dsBase
                - dsMediation        
    - role: service_minio
      vars:
        version: 2022-02-26T02-54-46Z
        data: /var/lib/minio/data
        protocol: http
        root_user: "{{ minio.root_user }}"
        root_password: "{{ minio.root_password }}"
        console: 
          version: 0.14.8
    - role: service_auth
      vars:
        image: 
          version: 0.3.2
          repo: molgenis
          name: molgenis-auth
        api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        base_url: http://armadillo-auth.local
    - role: service_rserve 
    - role: post_assemble
    - role: post_nginx
      vars:
        enabled: true
        domains: 
          armadillo: armadillo.local
          storage: "{{ minio.domain }}"
          console: "{{ minio.console.domain }}"
          auth: armadillo-auth.local
        letsencrypt:
          enabled: false
          acme: 
            email: user@example.org
    - role: tools_upgrade
      vars:
        enabled: true
