---
- hosts: all
  become: yes
  become_user: root
  gather_facts: yes
  vars:
    ci: false
    minio:
      access_key: molgenis
      secret_key: molgenis
      port: 9000
      host: http://localhost
    oauth:
      issuer_uri: https://auth.molgenis.org
      discovery_path: .well-known/openid-configuration
      client_id: xxxxx-xxxxxxxx-xxxxxxx
      client_secret: xxxxx-xxxxxxxx-xxxxxxx

  roles:
    - role: java
      vars:
        version: 11
    - role: minio
      vars:
        version: 2021-02-19T04-38-02Z
        data: /var/lib/minio/data
        domain: armadillo-storage.local:8080
        access_key: "{{ minio.access_key }}"
        secret_key: "{{ minio.secret_key }}"
    - role: podman
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"
    - role: docker
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
    - role: nginx_centos8
      vars:
        domains: 
          armadillo: armadillo.local
          storage: armadillo-storage.local
          auth: armadillo-auth.local
    - role: rserver
      vars:
        debug: false
        image:
          version: 2.0.1
        resources:
          memory: 6g
          cpu: 2
    - role: armadillo
      vars:
        version: 0.0.17
        storage:
          access_key: "{{ minio.access_key }}"
          secret_key: "{{ minio.secret_key }}"
          host: "{{ minio.host }}"
          port: "{{ minio.port }}"
        memory:
          xmx: 1024m
          xms: 512m
        username: xxxxxxx
        password: xxxxxxx
    - role: auth
      vars:
        image: 
          version: latest
          repo: molgenis
          name: molgenis-auth
        api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        base_url: http://armadillo-auth.local:8080
        resources:
          memory: 512m
          cpu: 1

