---
- hosts: all
  become: true
  become_user: root
  gather_facts: true
  vars:
    ci: false
    minio:
      access_key: molgenis
      secret_key: molgenis
      port: 9000
      host: http://localhost
    oauth:
      issuer_uri: https://auth.molgenis.org
      discovery_path: .well-known/openid-configuration
      client_id: xxxxxx-xxxxxxxxx-xxxxxxx
      client_secret: xxxxxxx-xxxxxxxxx-xxxxxxxx

  roles:
    - role: molgenis.molgenis8.java_ubuntu20
      vars:
        version: 11
    - role: molgenis.molgenis8.minio
      vars:
        version: 2021-02-19T04-38-02Z
        data: /var/lib/minio/data
        domain: armadillo-storage.local:8080
        access_key: "{{ minio.access_key }}"
        secret_key: "{{ minio.secret_key }}"
    - role: docker_ubuntu20
    - role: nginx_ubuntu20
      vars:
        domains: 
          armadillo: armadillo.local
          storage: armadillo-storage.local
          auth: armadillo-auth.local
    - role: rserver_ubuntu20
      vars:
        debug: true
        image:
          version: 1.8.0
        resources:
          memory: 6g
          cpu: 2
    - role: armadillo
      vars:
        version: 0.0.15
        storage:
          access_key: "{{ minio.access_key }}"
          secret_key: "{{ minio.secret_key }}"
          host: "{{ minio.host }}"
          port: "{{ minio.port }}"
        memory:
          xmx: 1024m
          xms: 512m
        username: admin
        password: admin
    - role: auth_ubuntu20
      vars:
        image: 
          version: latest
        api_token: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        base_url: http://armadillo-auth.local:8080
        resources:
          memory: 512m
          cpu: 1

