collections:
  - name: molgenis.molgenis8
<<<<<<< HEAD
    version: 1.1.1
=======
    version: 1.2.0
  - name: molgenis.armadillo1
    version: 1.1.0
>>>>>>> 1ce61c2... chore: added armadillo in requirements.yml
