---
baes_url: http://localhost:4000
oauth: 
  issuer_uri: https://auth.local
  client_id: xxxxxx-xxxxx-xxxx
  client_secret: xxxxx-xxxxx-xxxxxx
  api_token: xxxxxx-xxxxx-xxxxxx
  redirect_uri: http://localhost:4000/oauth-callback
image:
  version: 0.2.0
  repo: molgenis
  name: armadillo-auth
resources:
  memory: 1g
  cpu: 1

