---
galaxy_info:
  role_name: auth
  author: Sido Haakma
  description: Armadillo authentication implementation used allow people to use the Armadillo suite
  company: MOLGENIS

  license: LGPL

  min_ansible_version: 1.2

  github_branch: master

  platforms:
   - name: Ubuntu
     versions:
     - 20.04
  
  galaxy_tags: [federation]

allow_duplicates: true

dependencies:
  - { role: docker_ubuntu20 }
