---
- name: Install Python3.6 and pip3.6
  dnf:
    name:
      - python3
      - python3-pip
    state: present
  when:
    - ansible_distribution_major_version > '7'

- name: Install Python3.6 and pip3.6
  yum:
    name:
      - python3
      - python3-pip
    state: present
  when:
    - ansible_distribution_major_version == '7'
