---
- name: create folder for Armadillo auth logs
  file:
    path: "{{ item }}"
    state: directory
    mode: '755'
  with_items:
    - /usr/share/armadillo/auth
    - /var/log/armadillo/auth
    - /etc/armadillo/auth

- name: add logfiles for Armadillo auth
  file:
    path: /var/log/armadillo/auth/armadillo-auth-combined.log
    state: touch
    mode: '0644'
    modification_time: preserve
    access_time: preserve

- name: copy refresh script for Armadillo auth
  copy:
    src: refresh.bash
    dest: /usr/share/armadillo/auth
    mode: '750'

- name: generate start.bash for Armadillo auth
  template:
    src: start.j2
    dest: /usr/share/armadillo/auth/start.bash
    mode: '0750'

- name: generate install.bash for Armadillo auth
  template:
    src: install.j2
    dest: /usr/share/armadillo/auth/install.bash
    mode: '0750'
  notify: "refresh Armadillo auth service"

- name: generate env.list for Armadillo auth
  template:
    src: env.j2
    dest: /etc/armadillo/auth/env.list
    mode: '640'
  notify: "refresh Armadillo auth service"
