---

- name: Create certificate-directories for SSL
  file:
    path: /etc/pki/tls/certs/{{ inventory_hostname }}/
    state: directory
    mode: '0755'
  when: httpd.setup|bool and httpd.ssl|bool

- name: Install HTTPD virtualhost configuration with SSL
  template:
    src: vhost_ssl.j2
    dest: /etc/httpd/conf.d/{{ inventory_hostname }}.conf
    mode: '0755'
  when: not ci|bool and httpd.setup|bool and httpd.ssl|bool
  notify: "restart web services"

- name: Install HTTPD virtualhost configuration without SSL
  template:
    src: vhost.j2
    dest: /etc/httpd/conf.d/{{ inventory_hostname }}.conf
    mode: '0755'
  when: not ci|bool and httpd.setup|bool and not httpd.ssl|bool
  notify: "restart web services"
